### ISSUE TITLE
TypeError: complex_matmul() got an unexpected keyword argument 'bias_init_c'

### ISSUE THREAD

**Issue by SongRb** [v0lta/Complex-gated-recurrent-neural-networks#3] opened 2019-07-30 09:36 UTC
I have git cloned the repo and run `python bonn_eval_gate_diff.py`, but following error produced:

```
Traceback (most recent call last):
  File "bonn_eval_gate_diff.py", line 83, in <module>
    single_gate)
  File "/home/tang/Code/A20/Complex-gated-recurrent-neural-networks/synthetic_experiments.py", line 157, in main
    y_hat = tf.nn.dynamic_rnn(cell, x, dtype=tf.float32)
  File "/home/tang/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/tang/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/rnn.py", line 707, in dynamic_rnn
    dtype=dtype)
  File "/home/tang/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/rnn.py", line 916, in _dynamic_rnn_loop
    swap_memory=swap_memory)
  File "/home/tang/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3501, in while_loop
    return_same_structure)
  File "/home/tang/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3012, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/tang/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2937, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/tang/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3456, in <lambda>
    body = lambda i, lv: (i + 1, orig_body(*lv))
  File "/home/tang/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/rnn.py", line 884, in _time_step
    (output, new_state) = call_cell()
  File "/home/tang/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/rnn.py", line 870, in <lambda>
    call_cell = lambda: cell(input_t, state)
  File "/home/tang/Code/A20/Complex-gated-recurrent-neural-networks/custom_cells.py", line 930, in __call__
    bias_init=bias_init)
  File "/home/tang/Code/A20/Complex-gated-recurrent-neural-networks/custom_cells.py", line 859, in double_memory_gate
    bias_init_r=bias_init)
TypeError: complex_matmul() got an unexpected keyword argument 'bias_init_c'
```

**Comment by v0lta** [comment] 2019-07-30 09:47
Dear Song, thanks a lot for your feedback. It looks like you found a bug. Could you please try changing the keyword argument 'bias_init_c' into 'bias_init_i' ? I changed the header of the complex matmul function at some point and must have forgotten to update the double gating function.

**Comment by v0lta** [comment] 2019-07-30 10:08
Dear Song, i have pushed a fix. It should run now. Should you have any further trouble reproducing results please let me know.

**Comment by SongRb** [comment] 2019-07-31 04:10
Thanks for your response!

**Closed** 2019-08-03 14:43 UTC
Labels: bug
